"""Compose the research brief: deterministic data tables + cited LLM narrative.

Design rule: numbers are never generated by the LLM. The filed-financials
table is rendered directly from XBRL data; the LLM writes narrative *around*
the data and must cite the numbered sources for every paragraph.
"""

from __future__ import annotations

from .dossier import Dossier

DISCLAIMER = (
    "*tenq is an open-source research tool, not an investment adviser. "
    "This brief is generated from public filings and may contain errors. "
    "Nothing here is investment advice.*"
)

NARRATIVE_INSTRUCTIONS = """\
You are an equity research analyst. Using ONLY the dossier below, write the
narrative sections of a research brief on {company} ({ticker}).

Hard rules:
- Every claim must be supported by the dossier. If the dossier doesn't cover
  something, say so rather than guessing.
- Cite sources inline with bracketed reference numbers, e.g. [1], matching the
  numbered source list in the dossier. Every paragraph needs at least one citation.
- Use exact figures from the filed-financials table; do not invent or round
  beyond one decimal place.
- No price targets, no buy/sell/hold ratings, no return predictions.
- Markdown output with exactly these section headings (## level):
  Business snapshot, Financial trajectory, What management says (MD&A),
  Key risks (from the 10-K), Bull case, Bear case, What to watch next.
- Keep the whole narrative under 900 words. Plain, direct language.

DOSSIER:
{dossier_md}
"""


def _fmt(val: float, unit: str) -> str:
    if unit == "USD/shares":
        return f"{val:,.2f}"
    if abs(val) >= 1e9:
        return f"{val / 1e9:,.1f}B"
    if abs(val) >= 1e6:
        return f"{val / 1e6:,.1f}M"
    return f"{val:,.0f}"


def render_financials_table(dossier: Dossier) -> str:
    if not dossier.metrics:
        return "_No XBRL company facts available for this filer._"
    years = sorted({p.fy for s in dossier.metrics for p in s.points})[-5:]
    header = "| Metric (USD unless noted) | " + " | ".join(f"FY{y}" for y in years) + " | Source |"
    sep = "|" + "---|" * (len(years) + 2)
    rows = [header, sep]
    for s in dossier.metrics:
        by_fy = {p.fy: p for p in s.points}
        cells = []
        refs = []
        for y in years:
            p = by_fy.get(y)
            if p is None:
                cells.append("—")
            else:
                cells.append(_fmt(p.val, s.unit))
                ref = dossier.accession_refs.get(p.accn)
                if ref and ref not in refs:
                    refs.append(ref)
        label = s.label + (" ($)" if s.unit == "USD/shares" else "")
        ref_str = "".join(f"[{r}]" for r in sorted(refs)) or "—"
        rows.append(f"| {label} | " + " | ".join(cells) + f" | {ref_str} |")
    return "\n".join(rows)


def render_dossier_md(dossier: Dossier) -> str:
    parts = [f"# Dossier: {dossier.company} ({dossier.ticker}) — CIK {dossier.cik}"]

    parts.append("## Filed financials (SEC XBRL, exact values as filed)\n")
    parts.append(render_financials_table(dossier))

    if dossier.market:
        m = dossier.market
        items = ", ".join(f"{k.replace('_', ' ')}: {v:,}" if isinstance(v, (int, float)) else f"{k}: {v}"
                          for k, v in m.items())
        parts.append(f"\n## Market snapshot (indicative)\n\n{items}")

    if dossier.filing:
        f = dossier.filing
        parts.append(
            f"\n## Latest 10-K\n\nForm {f.form}, filed {f.filing_date}, "
            f"period ending {f.report_date}, accession {f.accession} "
            f"[{dossier.accession_refs.get(f.accession, '')}]"
        )
    if dossier.risk_factors:
        parts.append(f"\n## Item 1A — Risk Factors (verbatim extract)\n\n{dossier.risk_factors}")
    if dossier.mdna:
        parts.append(f"\n## Item 7 — MD&A (verbatim extract)\n\n{dossier.mdna}")

    if dossier.sources:
        parts.append("\n## Sources\n")
        for s in dossier.sources:
            parts.append(f"{s.ref}. {s.description} — {s.url}")

    return "\n".join(parts)


def build_prompt(dossier: Dossier) -> str:
    return NARRATIVE_INSTRUCTIONS.format(
        company=dossier.company,
        ticker=dossier.ticker,
        dossier_md=render_dossier_md(dossier),
    )


def compose_brief(dossier: Dossier, narrative: str | None) -> str:
    """Final markdown: header, narrative (if any), data appendix, sources."""
    parts = [f"# {dossier.company} ({dossier.ticker}) — research brief\n"]
    parts.append(f"Generated by [tenq](https://github.com/shahcolate/tenq) from SEC EDGAR primary sources.\n")

    if narrative:
        parts.append(narrative.strip())
    else:
        parts.append(
            "_Data-only dossier (run without an LLM provider). "
            "Set ANTHROPIC_API_KEY or OPENAI_API_KEY, or run Ollama, for the narrative sections._"
        )

    parts.append("\n---\n\n## Appendix: filed financials\n")
    parts.append(render_financials_table(dossier))

    if narrative is None:
        if dossier.risk_factors:
            parts.append(f"\n## Appendix: Item 1A — Risk Factors (extract)\n\n{dossier.risk_factors}")
        if dossier.mdna:
            parts.append(f"\n## Appendix: Item 7 — MD&A (extract)\n\n{dossier.mdna}")

    if dossier.sources:
        parts.append("\n## Sources\n")
        for s in dossier.sources:
            parts.append(f"{s.ref}. {s.description} — {s.url}")

    parts.append(f"\n---\n\n{DISCLAIMER}")
    return "\n".join(parts)
